USE [master]
GO

/****** Object:  Database [BotTrader]    Script Date: 2023-09-02 2:21:17 PM ******/
CREATE DATABASE [BotTrader]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BotTrader', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BotTrader.mdf' , SIZE = 532480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BotTrader_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BotTrader_log.ldf' , SIZE = 268160KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BotTrader].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BotTrader] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BotTrader] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BotTrader] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BotTrader] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BotTrader] SET ARITHABORT OFF 
GO

ALTER DATABASE [BotTrader] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BotTrader] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BotTrader] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BotTrader] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BotTrader] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BotTrader] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BotTrader] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BotTrader] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BotTrader] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BotTrader] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BotTrader] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BotTrader] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BotTrader] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BotTrader] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BotTrader] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BotTrader] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BotTrader] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BotTrader] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BotTrader] SET  MULTI_USER 
GO

ALTER DATABASE [BotTrader] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BotTrader] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BotTrader] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BotTrader] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BotTrader] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BotTrader] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BotTrader] SET QUERY_STORE = ON
GO

ALTER DATABASE [BotTrader] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BotTrader] SET  READ_WRITE 
GO

